### ISSUE TITLE
Traceback KeyError: 'id' on `snactor repo link`

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp#393]
With leapp-repository installed, I'm trying to create new actor repo and link it with the rest of the world.  This code used to work (with ~ leapp-0.3...):

    snactor repo new foo
    pushd foo
    snactor repo link --path /etc/leapp/repos.d/offline-upgrade
    snactor new-actor --tag IPUWorkflowTag --tag ApplicationsPhaseTag MyActor
    ...

Now the same code fails at the `snactor repo link ...` line, with this traceback:

    Traceback (most recent call last):
      File "/usr/bin/snactor", line 9, in <module>
        load_entry_point('leapp==0.4.0', 'console_scripts', 'snactor')()
      File "/usr/lib/python2.7/site-packages/leapp/snactor/__init__.py", line 68, in main
        cli.command.execute(version='snactor version {}'.format(VERSION))
      File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 80, in execute
        args.func(args)
      File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 102, in called
        self.target(args)
      File "/usr/lib/python2.7/site-packages/leapp/utils/repository.py", line 20, in checker
        return f(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/leapp/snactor/commands/repo/__init__.py", line 162, in link_repo
        if add_repository_link('.', get_repository_id(path)):
      File "/usr/lib/python2.7/site-packages/leapp/utils/repository.py", line 147, in get_repository_id
        return get_repository_metadata(path)['id']
    KeyError: 'id'

**Comment by AloisMahdal** [comment]
OK, turns out that the path is not valid anymore.  However, I guess an actuall error message would be better than traceback, so let's just say this is the proper interpretation of this Issue.

**Comment by AloisMahdal** [comment]
Sorry, my bad; fixed!
