### ISSUE TITLE
Upgrade failure due to missing leapp/dnf-plugin-data.txt

### ISSUE THREAD

**Issue by bxue** [oamg/leapp#449]
**Actual behavior**
'leapp upgrade --debug' fails with the following log.
It's a clean installed RHEL-7.6 Server system.
```
2019-02-20 17:45:56.151 INFO     PID: 6144 leapp.workflow.Download: Executing actor prepare_upgrade_transaction
Process Process-83:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 59, in _do_run
    target_actor(logger=logger, messaging=messaging).run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 228, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/prepareupgradetransaction/actor.py", line 286, in process
    error = self.dnf_plugin_rpm_download(ofs_info)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/prepareupgradetransaction/actor.py", line 193, in dnf_plugin_rpm_download
    with open(os.path.join(overlayfs_info.merged, 'var', 'lib', 'leapp', 'dnf-plugin-data.txt'), 'w+') as data:
IOError: [Errno 2] No such file or directory: '/var/lib/leapp/scratch/mounts/merged/var/lib/leapp/dnf-plugin-data.txt'

============================================================================================================
Actor prepare_upgrade_transaction unexpectedly terminated with exit code: 1 - Please check the above details
============================================================================================================

[root@VM ~]# ls /var/lib/leapp/scratch/mounts/merged/var/lib/leapp/
ls: cannot access /var/lib/leapp/scratch/mounts/merged/var/lib/leapp/: No such file or directory
[root@VM ~]# ls /var/lib/leapp/scratch/mounts/merged/var/lib/
rhsm  rpm
[root@VM ~]# rpm -q leapp
leapp-0.5.0-1.201902181202Z.28bb8bc.master.el7_5.noarch
[root@VM ~]# findmnt /
TARGET SOURCE                 FSTYPE OPTIONS
/      /dev/mapper/vg0-lvroot ext4   rw,relatime,data=ordered
[root@VM ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
[root@VM ~]# uname -a
Linux VM 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
**To Reproduce**
Steps to reproduce the behavior
1. leapp upgrade --debug

**Expected behavior**
Successful upgrade without error.

**System information (please complete the following information):**
 - OS and version: RHEL-7.6 GA
 - `# uname -a`: kernel-3.10.0-957.el7.x86_64
 - `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation): leapp-0.5.0-1.201902181202Z.28bb8bc.master.el7_5.noarch
```
# rpm -qa "leapp*"
[root@VM ~]# rpm -qa "leapp*"
leapp-deps-0.5.0-1.201902181202Z.28bb8bc.master.el7_5.noarch
leapp-0.5.0-1.201902181202Z.28bb8bc.master.el7_5.noarch
leapp-repository-deps-0.5.0-1.201902191106Z.8a99cb6.master.el7_5.noarch
leapp-repository-0.5.0-1.201902191106Z.8a99cb6.master.el7_5.noarch
leapp-repository-data-0.5.0-1.201902191106Z.8a99cb6.master.el7_5.noarch
```
 - attach (or provide link to) log files if applicable (optional - may contain confidential information):
   - **_/var/log/upgrade.log_**
   - */tmp/leapp-report.txt*
   - `# tar -czf dnf-debug.tgz /tmp/download-debugdata`
   - */var/lib/leapp/leapp.db*
   - *journalctl*
 - anything else you would like to provide (e.g. storage info):
```
NAME           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda            252:0    0   16G  0 disk
├─vda1         252:1    0  256M  0 part /boot
├─vda2         252:2    0  7.5G  0 part
│ ├─vg0-lvroot 253:0    0    5G  0 lvm  /
│ ├─vg0-lvswap 253:1    0    4M  0 lvm  [SWAP]
│ ├─vg0-lvhome 253:2    0  504M  0 lvm  /home
│ └─vg0-lvvar  253:3    0    4G  0 lvm  /var
└─vda3         252:3    0  8.3G  0 part
  └─vg0-lvvar  253:3    0    4G  0 lvm  /var
loop0            7:0    0    2G  0 loop /var/lib/leapp/scratch/mounts
```
****

**Additional context**
Please let me know if you need any other infomation, or login credential if needed. Thanks.

**Comment by Rezney** [comment]
@bxue Thanks for reporting this issue. We will move this to "leapp-repository" as it is related to upgrades.

I took a look at the machine and the issue seems to be related to the fact that there is "/var" filesystem on separate partition: 

```
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/vg0-lvroot     4.8G  1.1G  3.5G  25% /
devtmpfs                   1.2G     0  1.2G   0% /dev
tmpfs                      1.2G     0  1.2G   0% /dev/shm
tmpfs                      1.2G  8.6M  1.2G   1% /run
tmpfs                      1.2G     0  1.2G   0% /sys/fs/cgroup
/dev/vda1                  248M  115M  121M  49% /boot
/dev/mapper/vg0-lvhome     481M  2.3M  449M   1% /home
/dev/mapper/vg0-lvvar      3.9G  952M  2.8G  26% /var
```

And when in overlayfs container we see only:

```
[root@merged ~]# ls -la /var/lib/
total 20
drwxr-xr-x  4 root root 4096 Feb 21 17:16 .
drwxr-xr-x. 1 root root 4096 Feb 21 17:16 ..
drwxr-xr-x  5 root root 4096 Feb 21 17:16 rhsm
drwxr-xr-x  2 root root 4096 Feb 21 17:16 rpm
```

thus "dnf-plugin-data.txt" file cannot be created as it does not have whole path prepared. We will have to investigate this further.

@pirat89 @shaded-enmity @vinzenz  any ideas?
