### ISSUE TITLE
[snactor] Trace upon creating topic outside repository

### ISSUE THREAD

**Issue by fernflower** [oamg/leapp#456]
**Actual behavior**
If topic creation command is executed outside leapp repository a following stack trace is seen.
```Traceback (most recent call last):
  File ".venv/bin/snactor", line 10, in <module>
    sys.exit(main())
  File "/home/ivasilev/projects/leapp/.venv/lib/python3.7/site-packages/leapp/snactor/__init__.py", line 67, in main
    cli.command.execute(version=_('snactor version {}').format(VERSION))
  File "/home/ivasilev/projects/leapp/.venv/lib/python3.7/site-packages/leapp/utils/clicmd.py", line 80, in execute
    args.func(args)
  File "/home/ivasilev/projects/leapp/.venv/lib/python3.7/site-packages/leapp/utils/clicmd.py", line 102, in called
    self.target(args)
  File "/home/ivasilev/projects/leapp/.venv/lib/python3.7/site-packages/leapp/snactor/commands/new_topic.py", line 24, in cli
    basedir = os.path.join(basedir, 'topics')
  File "/home/ivasilev/projects/leapp/.venv/lib64/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**To Reproduce**
1. from any non-repo dir call snactor new-topic NewTopic

**Comment by vinzenz** [comment]
Yeah the command is missing the @requires_repository decorator
