### ISSUE TITLE
failing unit-tests for workflow APIs on python3.9.1 

### ISSUE THREAD

**Issue by pirat89** [oamg/leapp#690]
**Actual behavior**
Running unit tests on F33 (python-3.9.1) crashes on workflow APIs:
```
2021-02-22 16:17:07.128 DEBUG    PID: 34429 leapp.repository.workflow-api-tests: Starting actor discovery in actors/apiv2test
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pstodulk/special/leapp/leapp/leapp/repository/actor_definition.py", line 30, in inspect_actor
    definition.load()
  File "/home/pstodulk/special/leapp/leapp/leapp/repository/actor_definition.py", line 179, in load
    self._module = importer.find_module(name).load_module(name)
  File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 969, in load_module
  File "<frozen importlib._bootstrap_external>", line 794, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/actors/apiv2test/actor.py", line 3, in <module>
    from leapp.workflows.api.v2 import TestAPI
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/apis/v2/__init__.py", line 1, in <module>
    from leapp.workflows.api.v2.testapi import TestAPI
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/apis/v2/testapi.py", line 2, in <module>
    from leapp.workflows.api import v3
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/apis/v3/__init__.py", line 3, in <module>
    from leapp.workflows.api.v1.depcheck import DepCheckAPI1, DepCheckAPI2, DepCheckAPI3, DepCheckAPI4
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/apis/v1/__init__.py", line 1, in <module>
    from leapp.workflows.api.v1.testapi import TestAPI
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/apis/v1/testapi.py", line 5, in <module>
    class TestAPI(WorkflowAPI):
  File "/home/pstodulk/special/leapp/leapp/tests/data/workflow-api-tests/apis/v1/testapi.py", line 9, in TestAPI
    apis = (v2.TestAPI,)
AttributeError: partially initialized module 'leapp.workflows.api.v2' has no attribute 'TestAPI' (most likely due to a circular import)
2021-02-22 16:17:07.181 ERROR    PID: 34429 leapp.repository.workflow-api-tests: Process inspecting actor in actors/apiv2test failed with 1
Inspection of actor in actors/apiv2test failed

----------- coverage: platform linux, python 3.9.1-final-0 -----------
```
**To Reproduce**
On F33, with the current master branch (commit 8e3280a36e)
```
make install-test
make test
```

**System information:**

- OS and version: Fedora 33
- python3-3.9.1-2.fc33.x86_64

**Comment by pirat89** [comment]
@vinzenz something that could be interesting for you before we start the hackhaton :)
