### ISSUE TITLE
Upgrading RHEL7.9 to RHEL 8.4 on SAP environments - IOError: [Errno 2] No such file or directory: u'/etc/leapp/repos.d/system_upgrade/common/files/rhui/azure/content.crt'

### ISSUE THREAD

**Issue by PRELVAS94** [oamg/leapp#786]
**Actual behavior**

During the Leapp upgrade to RHEL 8.4 in a environment running the latest version of RH7.9 on Azure PAYG without RHSM creates a error IOError: [Errno 2] No such file or directory: u'/etc/leapp/repos.d/system_upgrade/common/files/rhui/azure/content.crt'

After running the command leapp preupgrade --no-rhsm --channel e4s --enablerepo rhel-8-for-x86_64-appstream-e4s-rhui-rpms --enablerepo rhel-8-for-x86_64-baseos-e4s-rhui-rpms --enablerepo microsoft-azure-rhel8-sap-ha 

==> Processing phase `TargetTransactionFactsCollection`
====> * target_userspace_creator
        Initializes a directory to be populated as a minimal environment to run binaries from the target system.
Process Process-448:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/actor.py", line 52, in process
    userspacegen.perform()
  File "/usr/lib/python2.7/site-packages/leapp/utils/deprecation.py", line 42, in process_wrapper
    return target_item(*args, **kwargs)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 673, in perform
    target_repoids = _gather_target_repositories(context, indata, prod_cert_path)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 616, in _gather_target_repositories
    rhui.copy_rhui_data(context, indata.rhui_info.provider)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/rhui.py", line 177, in copy_rhui_data
    context.copy_to(os.path.join(data_dir, path_[0]), path_[1])
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/mounting.py", line 233, in copy_to
    shutil.copy2(src, self.full_path(dst))
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/etc/leapp/repos.d/system_upgrade/common/files/rhui/azure/content.crt'

**To Reproduce**

During the Leapp upgrade to RHEL 8.4 in a environment running the latest version of RH7.9 on Azure PAYG without RHSM.

 leapp preupgrade --no-rhsm --channel e4s --enablerepo rhel-8-for-x86_64-appstream-e4s-rhui-rpms --enablerepo rhel-8-for-x86_64-baseos-e4s-rhui-rpms --enablerepo microsoft-azure-rhel8-sap-ha 

1. install '...'
2. setup '....'
3. run '....'
   (when run `leapp`, use always the `--debug` option to provide more data)

Process Process-448:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/actor.py", line 52, in process
    userspacegen.perform()
  File "/usr/lib/python2.7/site-packages/leapp/utils/deprecation.py", line 42, in process_wrapper
    return target_item(*args, **kwargs)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 673, in perform
    target_repoids = _gather_target_repositories(context, indata, prod_cert_path)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/targetuserspacecreator/libraries/userspacegen.py", line 616, in _gather_target_repositories
    rhui.copy_rhui_data(context, indata.rhui_info.provider)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/rhui.py", line 177, in copy_rhui_data
    context.copy_to(os.path.join(data_dir, path_[0]), path_[1])
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/mounting.py", line 233, in copy_to
    shutil.copy2(src, self.full_path(dst))
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/etc/leapp/repos.d/system_upgrade/common/files/rhui/azure/content.crt'

=========================================================================================================
Actor target_userspace_creator unexpectedly terminated with exit code: 1 - Please check the above details
=========================================================================================================
2022-07-22 17:33:47.870 INFO     PID: 10179 leapp: Answerfile will be created at /var/log/leapp/answerfile
2022-07-22 17:33:48.109 WARNING  PID: 10179 leapp.reporting: Stable Key report entry not provided, dynamically generating one - 29dc5fbec67feabdf323a3eed704a09b7cc38b7c
2022-07-22 17:33:48.314 WARNING  PID: 10179 leapp.reporting: Stable Key report entry not provided, dynamically generating one - 29dc5fbec67feabdf323a3eed704a09b7cc38b7

**Expected behavior**

A full upgrade from RHEL 7.9 to 8.4

**System information (please complete the following information):**

- OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
- `# uname -a`

linux 3.10.0-1160.71.1.el7.x86_64 #1 SMP Wed Jun 15 08:55:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):

leapp-upgrade-el7toel8-0.16.0-4.el7_9.noarch
leapp-rhui-azure-sap-1.0.0-1.el7.noarch
leapp-upgrade-el7toel8-deps-0.16.0-4.el7_9.noarch
leapp-deps-0.14.0-1.el7_9.noarch
python2-leapp-0.14.0-1.el7_9.noarch
leapp-0.14.0-1.el7_9.noarch
leapp-rhui-azure-1.0.0-2.el7.noarch

**Comment by MichalHe** [comment]
Hi @PRELVAS94, thank you for your detailed report and pointing out this issue.

I've checked the described behavior, and it is indeed a bug, due to an outdated `leapp-rhui-azure` package present in the RHUI repositories. This outdated `leapp-rhui-azure` does not yet reflect that since the the `v0.16.0` release of leapp-repository, the files necessary when upgrading RHUI systems need to be present elsewhere - the packages places these files into `/etc/leapp/repos.d/system_upgrade/el7toel8/files/rhui/`, whereas they need to be in `/etc/leapp/repos.d/system_upgrade/common/files/rhui`. Therefore, the workaround is straightforward - manually copying the files into the correct folder.

We will work on updating our RHUI-specific packages for Azure, and any updates regarding this bug will be posted in this issue.

**Comment by PRELVAS94** [comment]
HI Team,

Thanks for sharing the feedback. I solved it by using other repos… Here’s a small workaround I did for it to work

Next step is to make sure we have the appropriate packages in the repolist. One thing to make sure is that we do not have this following repo:

 

rhui-microsoft-azure-rhel7-base-sap-apps                                      Microsoft Azure RPMs for Red Hat Enterprise Linux 7 (rhel7-base-sap-apps)       

 

To get rid of it we will do the following :

 

Get inside /etc/yum.repos.d

 

And delete the following:

 

***@***.*** yum.repos.d]$ rm -rf  rh-cloud-base-sap-apps.repo

 

 

With the other repo deleted, we will need to configure this repo:

 

# yum --config='https://rhelimage.blob.core.windows.net/repositories/rhui-microsoft-azure-rhel7-base-sap-ha.config' <https://rhelimage.blob.core.windows.net/repositories/rhui-microsoft-azure-rhel7-base-sap-ha.config%27> install 'rhui-azure-rhel7-base-sap-ha’

**Comment by pirat89** [comment]
@PRELVAS94 Hi, I am sorry for the late response here. The issue around applications is fixed in the current upstream leapp-repository release (will be fixed officially during RHEL 8.8 GA date). switching to leapp-repository.
